### ISSUE TITLE
inputTail.multline.parser get extra ":" in fluent-bit conf file

### ISSUE THREAD

**Issue by lobida** [banzaicloud/logging-operator#900] opened 2021-12-31 07:07 UTC
Hello,

I'm using multline.parser but get fluent-bit config error, looks there's extra ":" on multiline.parser line:
logging config
-------------
logging.spec.fluent.bit

    inputTail:
      Docker_Mode: "Off"
      Refresh_Interval: "60"
      Rotate_Wait: "5"
      multiline.parser:
      - docker

fluent-bit conf
--------------
[INPUT]
    Name         tail
    DB  /tail-db/tail-containers-state.db
    Docker_Mode  Off
    Mem_Buf_Limit  5MB
    Parser  docker
    Path  /var/log/containers/*.log
    Refresh_Interval  60
    Rotate_Wait  5
    Skip_Long_Lines  On
    Tag  kubernetes.*
    multiline.parser**:** docker

logs: 
------------
[2021/12/31 06:49:49] [error] [config] tail: unknown configuration property '**multiline.parser**_**:**_'. The following properties are allowed: path, exclude_path, key, read_from_head, refresh_interval, watcher_interval, rotate_wait, docker_mode, docker_mode_flush, docker_mode_parser, path_key, offset_key, ignore_o
lder, buffer_chunk_size, buffer_max_size, skip_long_lines, exit_on_eof, skip_empty_lines, inotify_watcher, parser, tag_regex, db, db.sync, db.locking, db.journal_mode, multiline, multiline_flush, parser_firstline, parser_, and **multiline.parser**.                                                               
[2021/12/31 06:49:49] [ help] try the command: /fluent-bit/bin/fluent-bit -i tail -h

**Comment by ahma** [comment] 2022-01-17 13:14
Hi @lobida thanks for the report, I've tried to reproduce the issue on my side but this is looks fine for me. Could you please double check it ? 
Thanks!

**Comment by kenankule** [comment] 2022-02-25 16:09
I belive this is a duplicate of #888 and fixed in https://github.com/banzaicloud/logging-operator/releases/tag/3.17.0

**Comment by ahma** [comment] 2022-05-03 11:31
It seems fixed. Please reopen the ticket if it isn't.

**Closed by ahma** 2022-05-03 11:31 UTC
Labels: bug
