### ISSUE TITLE
Support for IAM Roles for Service Accounts for EKS

### ISSUE THREAD

**Issue by sudip-moengage** [banzaicloud/logging-operator#254] opened 2019-11-22 10:41 UTC
**Is your feature request related to a problem? Please describe.**
It is not a problem for me, for now I'll create access key and secret but would like to have support for IAM roles, so that only pods have needed iam role for the S3 output pligin or cloudwatch output plugin

**Additional context**
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Comment by ahma** [comment] 2019-12-07 20:53
I think the S3 output now has all the needed properties. Since the last release we added all the missing  auth configs to cloudwatch output #273 .You [can change](https://github.com/banzaicloud/logging-operator/tree/master/docs/security#deploy-with-kubernetes-manifests-1) the fluentd service account if you want. I'm going to close this ticket, but if you are missing anything please reopen it, and let us know.

**Comment by sudip-moengage** [comment] 2019-12-09 23:30
@ahma I couldn't test it, but I checked #273, I'm not proficient with go, but I can see support for assume instance role is there, which the pod can inherit from node.

But this issue is about kubernetes service account integration with AWS IAM roles. In short we do following:
- In AWS create roles with following policy:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "${OIDC_ARN}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "${OIDC_URL}:sub": "system:serviceaccount:${NAMESPACE}:${SA_NAME}"
        }
      }
    }
  ]
}
```
- In kubernetes we need to create a service account and annotate it with the role and use this service account in pods.

Then EKS automatically adds `AWS_ROLE_ARN`, `AWS_WEB_IDENTITY_TOKEN_FILE` (volume mount) env variable to pod. So, we need support for assuming roles via web identity token.

**Comment by ahma** [comment] 2019-12-09 23:45
Thanks @sudip-moengage , I will look into this. -> reopen

**Comment by ahma** [comment] 2019-12-20 16:00
@sudip-moengage In this case you can annotate the SA If you annotate the fluentd/fluentdbit resources [Docs](https://github.com/banzaicloud/logging-operator/blob/master/docs/crds.md#fluentd-spec)

**Comment by sudip-moengage** [comment] 2019-12-30 07:14
@ahma Yes, I can annotate but, the SDK fluentd uses, does it support `sts:AssumeRoleWithWebIdentity`?

**Comment by bonifaido** [comment] 2020-01-07 14:52
Hi @sudip-moengage,

the root cause for this issue is that the AWS Ruby SDK in the latest `fluentd-s3-plugin` doesn't support those environment variables injected by EKS in this case (`AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE`).

Please follow https://github.com/fluent/fluent-plugin-s3/issues/301 for further details. Once that plugin gets updated with a more up-to-date AWS Ruby SDK this will work automagically in more recent release of that plugin.

We can't solve this issue from the logging-operator, so I'm closing this now.

**Comment by bonifaido** [comment] 2020-01-10 08:48
@sudip-moengage just submitted https://github.com/fluent/fluent-plugin-s3/pull/305 to resolve the issue upstream, I hope it gets merged soon enough 🙂

**Comment by kostyaplis** [comment] 2021-04-21 04:09
@gregorygtseng seems that you are right. Having annotation set as `fluentd.annotations` annotates a fluentd pod, but not service account. Is there a way to let operator set SA annotation?

**Comment by pepov** [comment] 2021-04-21 06:24
no, currently you cannot

**Comment by kostyaplis** [comment] 2021-04-22 03:18
@pepov thanks for prompt reply
Shell we reopen this issue then? 
I confirm that SA annotation is the only missing feature to fully support IRSA for EKS.

**Closed** 2021-04-27 13:55 UTC
Labels: community, improvement, output
